### ISSUE TITLE
Download recording data

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bbb-playback#10]
Most of the recording data could be downloaded somehow for offline access.

**Comment by matiasilva** [comment]
Related issue: https://github.com/bigbluebutton/bigbluebutton/issues/1969?

This is the most commented on issue in the repo. Giving this a thumbs up.

**Comment by pedrobmarin** [comment]
Not entirely related with that issue since they're asking for something like a screen captured single video file of a recording. But we could plan on building a sort of an electron app of this player that loads and plays the recording data (chat, webcams, screenshare, presentation...) locally.

**Comment by matiasilva** [comment]
Ah I see. In this issue, you're considering the download of the individual files that make up the player and not a rendered version of the whole thing. Correct?

**Comment by hiroshisuga** [comment]
Although many people want this function. I feel this not really the first issue. I would not like my lecture downloaded as one video file and easily distributed in SNS by students. Even if this function is realized, the room owner should be the only person who can use it (or at lease the owner should be able to choose what to do).

**Comment by matiasilva** [comment]
For sure, I think only the owner should have access to the rendered version. It can be extremely useful however, to have one rendered version to upload to say YouTube or so.

**Comment by jibon57** [comment]
I did similar using puppeteer here: https://github.com/jibon57/bbb-recorder
As @pedrobmarin mentioned, building electron APP + puppeteer could be easy to resolve this. That time don't need `xvfb` or extra `chrome`.

**Comment by hiroshisuga** [comment]
I've found that bbb-playback has been implemented with the function "standalone playback". I guess it is what this thread is about. 
Already useful for playing back recordings in a different (web) server from the one running BBB, which may be busy with live lectures. A further function of automatic data transferring by sftp would be really nice!
