### ISSUE TITLE
How to set video speed 

### ISSUE THREAD

**Issue by jalodara** [bigbluebutton/bbb-playback#101]
"video": {
    "rps": 10,
    "rates": [ 0.5, 1, 1.5, 2 ]
  }
  
Can explain to set speed option in BBB video player,
and also how to set .VTT file option in player ?
skype : jalodaranaresh

Thanks

**Comment by pedrobmarin** [comment]
@jalodara , regarding the speed, you want to change to those values or you can find them in the player? VTT files normaly are provided by BigBlueButton's recording itself. You can experiment that out by enabling the closed captions and writing some stuff while recording.

**Comment by pedrobmarin** [comment]
I noticed you forked my personal repository. That one is outdated. We moved this project to the BigBlueButton umbrella, consider forking this repository instead https://github.com/bigbluebutton/bbb-playback
