### ISSUE TITLE
Remove the browser controls to download video portion of a recording

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bbb-playback#102]
Currently, users can right-click on the video portion of a recording and download it.

There are various methods to try and prevent the user from accessing this feature

 https://www.google.ca/search?q=disable+save+video+as&oq=disable+save+video+as

Need to investigate further whether in modern browsers any of these approaches would work for BigBlueButton's Presentation playback.

**Comment by amg-web** [comment]
is any suggest to add it myself on my server?
