### ISSUE TITLE
Slides are cropped

### ISSUE THREAD

**Issue by sparse91** [bigbluebutton/bbb-playback#138]
**Describe the bug**
Slides are zoomed in and cropped. The PNG slide file is OK.

**To Reproduce**
1. Open a recording!

**Expected behavior**
Slides should be shown in real aspect.

**Screenshots**
![image](https://user-images.githubusercontent.com/26763315/133934139-8f118202-2ab1-491a-94a0-a7d7c78166ff.png)

![image](https://user-images.githubusercontent.com/26763315/133934118-6668e47c-d9fd-4ce5-b4da-42600b92590d.png)

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Browser: Chrome and Firefox
 - Version: Latest versions

**Comment by sparse91** [comment]
More screenshots:
![image](https://user-images.githubusercontent.com/26763315/133934478-04a7e508-0593-4831-aae0-a2b61edf563f.png)



PNG file:
![image](https://user-images.githubusercontent.com/26763315/133934513-8b224690-2b62-4b1c-b45c-1ab15a13e4fd.png)

**Comment by pedrobmarin** [comment]
Maybe something went wrong at the processing stage.
- Could you share the presentation file you used?
- Was the file pre-loaded using the API?
- Can you reproduce this with other files?

**Comment by sparse91** [comment]
Sorry. Teachers had zoomed in slides during class. There is no problem in bbb. I removed their zooms by editing panzooms.xml.
