### ISSUE TITLE
How can use query string to show recordings in different folder?

### ISSUE THREAD

**Issue by amirazad1** [bigbluebutton/bbb-playback#141]
I use "https://server/playback/presentation/2.3/recordId?p=test" for playing my recordings at
 **/var/bigbluebutton/published/presentation/test**   folder. I get error 404.
What am I doing wrong?

**Comment by pedrobmarin** [comment]
Check on your browser's logs (console and network) if the recorded files are being fetched from the path you'd expect them to be. Here's the list of most of the files used by the playback: https://github.com/bigbluebutton/bbb-playback/blob/9e819a7c42627e9886085752f4f6ec1421d608dc/src/config.json#L14-L26

**Comment by amirazad1** [comment]
@pedrobmarin thanks ....with your help i found problem that was for permission to custom folder.
