### ISSUE TITLE
Transfer of 2.2 recordings to new 2.3 server - will not play

### ISSUE THREAD

**Issue by mudislandkid** [bigbluebutton/bbb-playback#144]
**Describe the bug**
I setup a new 2.3 instance on a clean ubuntu 18 server. I migrated greenlight and everything works fine. I can start a room, record and playback that recording with no issues. I then transferred my recordings from the 2.2 server as shown in the documentation. These all show up correctly and when I click to play one the player will load and display any notes and the slides. However, when I click play it freezes as if trying to load the webcams, then after a while gives an error that it cannot find the media. I've checked the recordings folder and there is a webcam file. I see a previously closed issue here similar to this ut it refers to audio only recordings whereas this is happening for every 2.2 originating recording.

I've been trying to resolve this for the past two days. I tried the workaround of changing the default player back to 2.0 however although that load the old player, the same issue persists.

**To Reproduce**
1. Install BBB 2.3 on fresh ubuntu 18 server with greenlight
2. transfer greenlight DB and STORAGE and .env and docker-compose.yaml to new server
3. update secret to new server
4. BBB loads fine and can run and record a session and playback new session.
5. rsync records from the old 2.2 server to new 2.3 instance
6. restart
7. BBB lists all 2.2 recordings
8. Click on recording to play, it will load the 2.3 player and display notes and slides etc
9. Press play button and player will hang before eventually stating it cannot find the media or it might not be in the right format.

**Expected behavior**
transfer 2.2 recordings to 2.3 instance, play recording and it plays correctly in 2.3 player OR it automatically identifies it is a 2.2 recording and plays it in the 2.2 player with no issues.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser safari, chrome, firefox
 - Version BBB v2.3

**Comment by pedrobmarin** [comment]
Hi @mudislandkid ,

This is not a playback issue. The player is fully compatible with v2.2 recordings.

Try reaching out with greenlight developers at it's repository. One more question -- are you also running scalelite? Saw several people having some trouble migrating scalelite https://github.com/blindsidenetworks/scalelite/releases/tag/v1.1. If that's the case, try checking scalelite repository too.

**Comment by mudislandkid** [comment]
> Hi @mudislandkid ,
> 
> This is not a playback issue. The player is fully compatible with v2.2 recordings.
> 
> Try reaching out with greenlight developers at it's repository. One more question -- are you also running scalelite? Saw several people having some trouble migrating scalelite https://github.com/blindsidenetworks/scalelite/releases/tag/v1.1. If that's the case, try checking scalelite repository too.

Thank you. I'm having the issue both with greenlight as my front end and also when doing this through moodle too so I'm not sure it has anything to do with Greenlight? And no, not on scalelite.

**Comment by pedrobmarin** [comment]
You can add a `debug` param to your recording url (e.g: https://host/playback/presentation/2.3/id?debug) and check browser's console logs and network to make sure which files aren't being loaded for further investigation. You can also try the [bigbluebutton-setup mailing list](https://groups.google.com/g/bigbluebutton-setup).
