### ISSUE TITLE
BBB 2.3.15 iOS Screen share video not working

### ISSUE THREAD

**Issue by waesien** [bigbluebutton/bbb-playback#154]
**iOS Screen share video not working;**

Phone: iPhone 11
iOS Version: 15.0
Browser: safari, chrome, edge

![image](https://user-images.githubusercontent.com/81984557/138566071-8505e9a1-68fe-466d-b43a-c6727e54cf08.png)

**Android no problem;**

![image](https://user-images.githubusercontent.com/81984557/138566077-2e0c803d-3407-4c2a-a4bb-c7a684b3ba1f.png)

**Comment by MBM1607** [comment]
@waesien  this maybe due to screen share video only being available in .webm format.

You need to enable recording in mp4 so it can be played on IOS devices as well.

https://docs.bigbluebutton.org/admin/customize.html#enable-playback-of-recordings-on-ios

**Comment by ffdixon** [comment]
Thanks @MBM1607 for helping out.  Closing this issue.
