### ISSUE TITLE
Playback Recordings from AWS S3 (BBB 2.3, 2.4)

### ISSUE THREAD

**Issue by gpallaris** [bigbluebutton/bbb-playback#156]
How can we configure bbb-playback 2.3/2.4 to playback recordings from an S3 Bucket?

For BBB 2.2 we could edit writing.js :
const url = “https://BUCKET.s3.eu-west-2.amazonaws.com/“+meetingId;
//const url = getFullURL();

But what about 2.3 and 2.4? Wow how can we do something similar to 2.3? I cant find any similar setting.

Thank you in advance
George

**Comment by pedrobmarin** [comment]
Did you try this one https://github.com/bigbluebutton/bbb-playback#external-recordings ?

**Comment by gpallaris** [comment]
> Did you try this one https://github.com/bigbluebutton/bbb-playback#external-recordings ?

The instructions state that  we have to Build BBB Playback.
 In our case we setup BBB using BigBlueButton official bbb-install.sh script. How can we REBuild just the BBB Playback ?

"To do this, build the bbb-playback with the following options:

REACT_APP_MEDIA_ROOT_URL=/different/relative/path/to/presentation/files npm run-script build
You can also play medias from an external server. Note that you will need to have the Access-Control-Allow-Origin header returned on the medias for that to work.

REACT_APP_MEDIA_ROOT_URL=https://my-media-server.example.com npm run-script build"

**Comment by pedrobmarin** [comment]
Yea. The same README file gives instructions on how to build it.

**Comment by gpallaris** [comment]
> Yea. The same README file gives instructions on how to build it.

Great! I managed to build it ! Thanks alot!
