### ISSUE TITLE
Update the slide when the corresponding thumbnail is clicked

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bbb-playback#160]
**Is your feature request related to a problem? Please describe.**
I am using BBB playback for showing questions of an exam (one question in each slide, showing one slide for ~10s). For that purpose, students may want to navigate the questions by clicking the thumbnails. But currently, they need to click the play button and pause it quickly to update the slide (question). 

**Describe the solution you'd like**
Even when the player is paused, update the slide when a thumbnail is clicked. 

**Additional context**
The 2.0 player automatically starts playing when you click the thumbnail with the player paused. So students need to quickly pause the player to read the question. But it was just one click, and I can even modify the code so that it does not automatically start.
On the other hand, the 2.3 player does not start automatically when a thumbnail is clicked with the player paused, which is in a sense good for the exam. But instead they need to click the play button twice quickly to update the question.... If the 2.3 player reload the slide immediately by clicking thumbnail with the player yet paused, it perfectly meets our requirement. And I believe this feature is also convenient for most of the users as well.

**Comment by pedrobmarin** [comment]
Hi @hiroshisuga thanks for the feedback.

I noticed the same UX problem myself. I'll try to take a look on this before the next v2.4.x release.

**Comment by pedrobmarin** [comment]
Did a simple change over the player dispatcher ^. Could you give it a try, @hiroshisuga ?

**Comment by hiroshisuga** [comment]
I've confirmed that it works as expected. Great!
But why at player.webcam even if there is no webcam in the recording? Just curious.

**Comment by pedrobmarin** [comment]
It's just how BBB recordings work... Even if no webcam was recorded or shared during the meeting, BBB will generate a video media (in this case blank one). This is particularly important because you can't add the closed captions to audio files (as far as I know).

A couple of years back the record and processing module did generate audio files for those cases and the playback have a fallback for those. This fallback uses the same "webcam" component for those audio files because they share the same media container (webm). So player.webcam is also the audio primary media on this scenario.

**Comment by pedrobmarin** [comment]
Here's where I included the audio support https://github.com/bigbluebutton/bbb-playback/pull/145

**Comment by hiroshisuga** [comment]
I see. Some history behind...

**Comment by hiroshisuga** [comment]
Hi @pedrobmarin , sorry for reviving the thread.
I have just realised that there is a strange phenomenon that I cannot select one thumbnail, I mean, when I click one thumnail, there is two thumbnails selected. When this happens, the slide update does not work. It happens on Chrome, Edge, and Brave, but on Firefox it does not happen...
This is probably unrelated to this PR. Let me know if I can check something.
![Animation1](https://user-images.githubusercontent.com/45039819/150890434-d88b83aa-aad6-4dc9-b2ed-d23688bbf2e4.gif)

**Comment by hiroshisuga** [comment]
This happens on the data recorded both on BBB2.2.x and BBB2.3.x.

**Comment by pedrobmarin** [comment]
Hi @hiroshisuga . Thanks for reporting.

I'll move your comment to a new issue to check it out later.
