### ISSUE TITLE
Only one locale is shown for multiple closed captions

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bbb-playback#164]
**Describe the bug**
Even when you set up multiple closed captions with different languages, only one locale is shown in the playback.

**To Reproduce**
1. Start a meeting and recording
2. Start multiple closed captions with different locales
3. In the playback only one locale is shown in the CC dropdown, most likely the lastly started one.

**Expected behavior**
You want to select one locale from the list of all locales used in the meeting.

**Comment by pedrobmarin** [comment]
Hi @hiroshisuga ,

I tested this over BBB v2.4 and got the multiple captions as CC options:
![cc](https://user-images.githubusercontent.com/1778398/153597606-55d06075-b3af-4d6b-8a61-09c2ebf3f699.png)

Could this be a problem introduced at playback's develop branch?

**Comment by hiroshisuga** [comment]
I thought I am using the production version, but obviously something is wrong. I will take a look. Thanks for testing it!

**Comment by pedrobmarin** [comment]
Production should be building over the master branch. Maybe I introduced some regression in between those.

**Comment by hiroshisuga** [comment]
I found only one language file generated in the /var/bigbluebutton/published/... directory. So it probably accounts for my developing BBB branch. But it is weird because I only touch HTML5 client...

**Comment by hiroshisuga** [comment]
Thanks @pedrobmarin , anyway it's not a problem in the player. I post this in the google group bigbluebutton-dev.

**Comment by pedrobmarin** [comment]
This was how the closed captions feature was conceived way back with the Flash Client. When the HTML5 client was developed it had to interoperate with this previous version so many things did not change at the backend.
