### ISSUE TITLE
Locale selector mispositioned

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bbb-playback#166]
**Describe the bug**
When a closed caption is on, the player shows the selector in a wrong place <s>and strange characters are shown on the right of the items</s>.

**To Reproduce**
1. start a meeting with a closed caption
2. open the record by the player
3. click the CC button

**Screenshots**
![1 0](https://user-images.githubusercontent.com/45039819/153743598-d439da5c-934b-4b32-b0b6-71a485e68fc9.jpeg)

<s>When I pull the dropdown to the left by the developer tool, strange letters appear on the right. </s>

<s>When I use only English caption, the problem still happens. Changing the language of the browser and the HTML5 client does not help.</s>

**Desktop (please complete the following information):**
 - Windows 10 (Japanese)
 - Chrome, Edge, Firefox

**Comment by pedrobmarin** [comment]
Hmmm, just noticed we already had this reported a while back over #103 . Closing this one in favor of the first report. Thanks @hiroshisuga .
