### ISSUE TITLE
Replace xml2js with a frontend-compatible XML parser

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bbb-playback#191]
**Is your feature request related to a problem? Please describe.**
[CRA v5+](https://github.com/facebook/create-react-app/releases/tag/v5.0.0) uses webpack 5 which has [removed automatic Node.js polyfills](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed). [xml2js](https://www.npmjs.com/package/xml2js) depends on `sax` and I'm guessing this lib relies on some Node.js polyfills such as `timers`. 

**Describe the solution you'd like**
Replace xml2js with a frontend-compatible XML parser.

**Describe alternatives you've considered**
Other options would be ejecting the project from CRA or even use [CRACO](https://www.npmjs.com/package/@craco/craco) to map webpack missing dependencies. The first thing I would try it out would be a frontend-compatible approach as [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser).

**Comment by MBM1607** [comment]
So if I understand this correctly, you want to update to CRA v5+ but xml2js is the bottleneck preventing from doing so. Is that right?

**Comment by pedrobmarin** [comment]
Yes, something like that.

Currently there's no simple way to test this. If I was the one to do this, I'd try to replace these https://github.com/bigbluebutton/bbb-playback/blob/a3e9136fa8015c2f09f354ee85d4cb18cbf03859/src/utils/builder.js#L529-L556 , one by one, and check if the modifications match the same result we have using xml2js . You will need a recording with some chat messages, some slides with multiple types of annotations, pan and zoom and screenshare.
