### ISSUE TITLE
Improve localization

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bbb-playback#197]
**Is your feature request related to a problem? Please describe.**
The locale automated selector tries a language over a regional and, for cases like Persian where there is the regional available but not the root language option, the fallback will go to English losing all RTL aspect of the player.

**Describe the solution you'd like**
Try matching the language in both directions, regional to root and root to regional.

**Describe alternatives you've considered**
BigBlueButton's HTML client has a solution for something similar. Maybe bring that implementation over this.

**Comment by MBM1607** [comment]
@pedrobmarin  I would like to take development for this, but I am afraid I don't understand the issue enough to be able to replicate this. Could you perhaps clarify what you mean by regional?

**Comment by pedrobmarin** [comment]
Hi @MBM1607 , thanks for showing interest in contributing with this project.

The `region` I meant was the region [subtag](https://datatracker.ietf.org/doc/html/rfc5646#section-2.2.4) at the language tag.

The problem I noticed about localization is that some languages only have a regionalized option at [BigBlueButton's Transifex project](https://www.transifex.com/bigbluebutton/bigbluebutton-v24-html5-client). The Persian Farsi is an example, where there's only it's [Iranian version](https://github.com/bigbluebutton/bbb-playback/blob/3e9e59a1ba3e3d6bbf05e5c080f5c0a7a5c6e368/src/locales/messages/index.js#L20).

Right now, if anyone tries to load the playback with only the Farsi root (fa) set as the browser's language, it will get the default English fallback because we do not check if any regionalized option can cover that language.

I guess an easy way to avoid this would be making sure all root languages get a regionalized fallback if they are not covered by BigBlueButton's locales. Not an ideal solution but could definitely solve this problem. Something like, at https://github.com/bigbluebutton/bbb-playback/blob/develop/src/locales/messages/index.js :
```
const messages = {
  ...
  fa: fa_IR,
  fa_IR,
  ...
}
```

**Comment by MBM1607** [comment]
@pedrobmarin  Another solution could be to detect if there are any locales starting with the current root. This only in case no root locale exist. The issue I had with this approach is that it would choose any one of the given regions at random in cases when multiple are available like 'Chinese'.

```file = Object.keys(messages).find(message => message.startsWith(language))```
