### ISSUE TITLE
Can you please include the unminified video-js.min.css file in public/styles

### ISSUE THREAD

**Issue by isatti** [bigbluebutton/bbb-playback#198]
By including the unminified file public/stylesvideo-js.min.css It would ease future contribution and independent development
to the project. An example is the menu for captions which is a little right off the screen. A simple fix for that is changing
font-weight:700;cursor:default}.vjs-menu-button-popup .vjs-menu{display:none;position:absolute;bottom:0;width:10em;**left:-3em**;height:0;margin-bottom:1.5em;border-top-color:rgba(43,51,63,.7)}
to 
font-weight:700;cursor:default}.vjs-menu-button-popup .vjs-menu{display:none;position:absolute;bottom:0;width:10em;**left:-6em**;height:0;margin-bottom:1.5em;border-top-color:rgba(43,51,63,.7)}
but due to the minified file maintaining is difficult. So an unminified file would do wonders for it.
Thank you
![Screenshot (7)](https://user-images.githubusercontent.com/22918741/165459520-161175ec-118b-4cf0-9cdd-342dedc311aa.png)

**Comment by pedrobmarin** [comment]
We usually overwrite video-js' classes over here https://github.com/bigbluebutton/bbb-playback/blob/develop/src/components/webcams/index.scss . As a matter of fact, a couple of months ago we included a fix for the captions popup, you might want to update your bigbluebutton setup.
