### ISSUE TITLE
Presentation of Poll results in Public Chat: absoulte numbers missing

### ISSUE THREAD

**Issue by LupoWM** [bigbluebutton/bbb-playback#218]
**Describe the bug**
when publishing the results of a poll, a popup window shows for each option (i) the absolute number of votes and (ii) the percentage.
In the public chat and in the recording(!), only the percentage is shown.  The total numbers are missing. 
This is e.g. a problem in polls where one is interested in the total numbers (maybe small numbers amongst > 100 students).

Additional minor bug: when having a "User Response" poll where students are told to enter "A"... "H" for eight possible options, 
the result in the popup window (usually correctly)  identifies "a" and "A", while in the chat both are counted as separate options (in the screenshot below: "f" and "F").

**To Reproduce**
* do such a poll ;)
* see e.g.  at <https://meet.gwdg.de/playback/presentation/2.3/9b85104f80734d3880260c6176c3f4cf2cc1fb71-1666785008279> 
  at 00:23:06
* <https://meet.gwdg.de/playback/presentation/2.3/c35fc0e1dad78bd7b5bb2aec14738c45b8ad9314-1666698943311>
  at 00:22:30
 (I hope that both are accessible from outside our university).
 In both cases, there are more poll results visible in the chat.

**Expected behavior**
Chat output of poll should contain option + absolute number of votes + percentage.

**Screenshots**
Screenshot: 
![pollresult](https://user-images.githubusercontent.com/117123878/199117530-4fcf64a0-b16f-422b-becb-0512d45b819d.png)

**Comment by pedrobmarin** [comment]
Thanks for reporting.
@germanocaumo could you take a look in this one?
