### ISSUE TITLE
Skip playback by arrow button

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bbb-playback#22]
**Is your feature request related to a problem? Please describe.**
With the playback 2.0 using popcorn.js, the user can skip the playback by one second back and forward pushing the keyboard arrow button. Keep pushing the arrow button leads to the fast forwarding the playback. The new playback 2.3 does not seem to have implemented this function.

**Describe the solution you'd like**
I would love to have the same function. The students often want to go back or forward by relatively short time (like 5 seconds), to listen back what the teachers say or skip the stupid troubles in the teacher's side. 

**Alternative**
Having buttons like [-5s] [5s] in the controler.

**Additional context**
Congratulations @pedrobmarin for the nice playback interface. I really like it!

**Comment by pedrobmarin** [comment]
Hi @hiroshisuga , thx! Glad you like it.
I believe you can have a similar behaviour when your browser focus is at video.js progress control. But we could discuss global shortcuts like this one.

**Comment by hiroshisuga** [comment]
By default no function seems to be assigned to the arrow keys. But I also believe that implementation should not be very difficult. Thank you for considering.

**Comment by hiroshisuga** [comment]
Hi @pedrobmarin ,
I did a small modification for arrow key shortcut.
At line 143 of src/components/video/index.js
          vertical: true,
        },
      },
// start from here
    userActions: {
      hotkeys: function(event) {
        // `->`
        if (event.which === 39) {
          let time = this.currentTime() + 5;
          this.currentTime(time);
        }
        // `<-`
        if (event.which === 37) {
          let time = this.currentTime() - 5;
          if (time < 0) {
            time = 0;
          }
          this.currentTime(time);
        }
      }
    },
// until here
      controls: true,
      fill: true,

These change just works for 5 sec forward and reverse the presentation. Use this if you want.

**Comment by megamind89** [comment]
Hi @pedrobmarin, great work on the playback interface and its going smooth so far. I had a request pertaining to this enhancement. Its already handy to have keyboard shortcuts merged to the interface, however if it were possible to add the alternative solution suggested here by @hiroshisuga, in the spirit of PDA users, it would be further beneficial. I was trying to integrate videojs-seek-buttons (npm module) but was not successful so far. It would help if you could guide me to include just a bare minimum of the functionality i.e., just the seek forward and backward as buttons in the control bar. Thanks for your time.
