### ISSUE TITLE
Seek buttons for handhelds

### ISSUE THREAD

**Issue by megamind89** [bigbluebutton/bbb-playback#228]
**Is your feature request related to a problem? Please describe.**
A feature request to enhance existing functionality. Issue #22  #25 

**Describe the solution you'd like**
Its already convenient to have keyboard shortcuts available for seeking the recording playback forward and backward by predefined seconds. However, if it were possible to extend these capabilities to PDA users since bigbluebutton works pretty well on handhelds as well. Maybe having a >> or << buttons next to the play button on the control bar of the player. 

**Describe alternatives you've considered**
1: I tried to include the videojs-seek-buttons module by mister-ben into the application but I am not able to figure out where and how to include within react.
2: I tried to include a button to the player and call a function which can trigger the keyboard event  alt+shift+'->' but seems like the player isn't picking it up or I am doing something wrong. Including the snippet here. I tried to include this from the console of the browser just to test, since I am not comfortable with react. 

//code 
function seekforward(){
  document.dispatchEvent(new KeyboardEvent("keydown", {
keyCode: 39,
which: 39,
altKey: true,
shiftKey: true
})
);
} 

**Additional context**
If it were possible to extend support it would be great help. Huge thanks to the authors for such simple yet efficient player!

**Comment by pedrobmarin** [comment]
I used this same plugin for a different project and worked quite well... if it's something the BigBlueButton project would like to have in the playback I guess folks from Mconf could try porting that to this app.

**Comment by megamind89** [comment]
Thank you @pedrobmarin, for your reply. Meanwhile, anything that you can guide me with so that I can have a workaround for the time being. Something on the grounds of the second alternative mentioned or even better?

**Comment by pedrobmarin** [comment]
I'd try again the plugin. That should be the easiest way to get this working. I don't think you need any react-like implementation for it, only the default setup of a videojs plugin and there's a ton of docs of that on the Internet.

**Comment by germanocaumo** [comment]
Hey @megamind89, I had a try and looks like it worked, please have a look:
https://github.com/bigbluebutton/bbb-playback/pull/229
