### ISSUE TITLE
Slides and drawings are cropped

### ISSUE THREAD

**Issue by davidrojo** [bigbluebutton/bbb-playback#248]
**Describe the bug**
Whe playing a recording, the image and drawings are cropped

**To Reproduce**
You can see a demo at https://virtual.asesacademia.com/playback/presentation/2.3/268837734e0b69631a64172a71a37f7540d62f58-1690634858110

At minute 3:30 you can see the text and the drawing is cropped.

**Expected behavior**
The image and the drawings should fit the rectangle and be visible.

**Desktop (please complete the following information):**
 - OS: Any OS
 - Browser Any browser

**Comment by ffdixon** [comment]
Good catch!  We just tried a demo with the attached slide, but it didn't get cropped

<img width="1431" alt="image" src="https://github.com/bigbluebutton/bbb-playback/assets/290351/6c39cc2a-1db8-461a-a3eb-9197463451bd">


Can you attache your slides so we could reproduce.

[cropped.pdf](https://github.com/bigbluebutton/bbb-playback/files/12209275/cropped.pdf)

**Comment by davidrojo** [comment]
Hi Fred,

This is the file used: 

[Classes de Teoria.pdf](https://github.com/bigbluebutton/bbb-playback/files/12213018/Classes.de.Teoria.pdf)

Looks like is something related to the zooms, at minute 3:06 you can see the teacher is writing a rectangle outside the viewing area.

The teacher has commented me, that the zoom in his computer is a little laggy, maybe this caused that the teacher was seeing some zoom level, but bbb was storing another zoom level?
