### ISSUE TITLE
Whiteboard drawings not shown when drew->all cleared->drew

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bbb-playback#26]
**Describe the bug**
The whiteboard drawing are not shown, when users drew things, everybody removed it (so nothing shown), and then they started to draw again in one presentation slide.

**Additional context**
I looked into the problem and found out that in getCurrentDataInterval function, the program defines the range of canvas data by checking if the drawing is active or not. It surveys the data from the beginning, and stops when the first inactive drawing is spotted out after the first active drawing is recognised. Thus, when the users (or room owner) clears up the drawing once, and then restart to draw, the latter drawings would not be played back. 
I have implemented a solution and now watching if it works as I intended. I will post it as PR later.

**Comment by pedrobmarin** [comment]
Hi @hiroshisuga . Thanks for the feedback.

Is this somehow related with multi-user whiteboard? I'm not sure if I understood the steps to reproduce this issue.

**Comment by hiroshisuga** [comment]
Yes. This happened to me when I ask the students to draw lines on the multiuser mode. The version 2.0 playback worked without problem.

**Comment by pedrobmarin** [comment]
Tried to reproduce it a couple of times but could not detect the problem. I'll wait your PR to get a better glimpse of this issue.

**Comment by hiroshisuga** [comment]
I am sorry that I cannot clearly show the issue. There seems to be the case where the canvas drawing data are, e.g. inactive, inactive, active, active, inactive, inactive, active, active, inactive. In this case the current app processes only the first 4 data (showing the 2nd and 3rd data), ignoring the 6th and 7th data.

**Comment by pedrobmarin** [comment]
That would be very helpful.

**Comment by hiroshisuga** [comment]
Am I  reaching you by this address, @pedrobmarin ?

2020年6月18日(木) 22:32 Pedro Beschorner Marin <notifications@github.com>:
