### ISSUE TITLE
Maximize the slide in smartphone

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bbb-playback#37]
**Is your feature request related to a problem? Please describe.**
This is not really a problem, but I feel a bit frustrated with the small sized slide shown in the smartphone screen.

**Describe the solution you'd like**
Currently the slide panel and chat panel are equally distributed in size. Usually students want to see the slide more than the chat (at least teachers want them to do so;-). Wouldn't it be better to maximize the slide panel and squeeze the chat panel (which can be scrolled anyway) in the rest of the screen? 

**Describe alternatives you've considered**
An easy trick is for instance 
to modify line 28 of src/components/index.scss as
grid-template-rows: $navigation-bar-height 3fr 2fr $action-bar-height
![名称未設定 2のコピー](https://user-images.githubusercontent.com/45039819/85381313-d0159600-b578-11ea-9e38-40561c88bbed.jpg)
![名称未設定 1のコピー](https://user-images.githubusercontent.com/45039819/85381328-d277f000-b578-11ea-94b1-7cded6a360e1.jpg)

**Comment by pedrobmarin** [comment]
A fullscreen for the content area is already implemented.

![fullscreen](https://user-images.githubusercontent.com/1778398/85394836-910a2500-b525-11ea-89be-c397623020fa.gif)

**Comment by hiroshisuga** [comment]
Wow. Thanks a lot!
