### ISSUE TITLE
Improve localization

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bbb-playback#4]
We have `en` and `pt` right now and this could easily grow a couple more languages.

**Comment by antobinary** [comment]
What file would have to be included to Transifex? Have you considered using the same key-value pairs as the HTML5 client to reuse translations?

This would also lead to Right-To-Left languages support

**Comment by pedrobmarin** [comment]
The locale files are kept here https://github.com/bigbluebutton/bbb-playback/tree/master/src/locales/messages. It can use the same BBB does but I'm not sure if we can map everything from there. RTL would be great too

**Comment by pedrobmarin** [comment]
Just included some extra languages support. Used a simple translator set the first locale values so I'm not sure how correct they are.
Also included RTL support:
![rtl](https://user-images.githubusercontent.com/1778398/83668945-29585e00-a5a7-11ea-8aa1-67d9defbf45a.png)

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/bbb-playback/commit/4293b1fa1225bdb68e012f834e68919d5b746ce4 and https://github.com/bigbluebutton/bbb-playback/commit/1cc83a7d9febc4ad5fedac29acfc54824318ace0.
