### ISSUE TITLE
Polls don't render on recording processed with 2.3 processing scripts

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bbb-playback#75]
In recordings processed with newer versions of the presentation processing script, polls don't render in bbb-playback.

The reason is related to the code at https://github.com/bigbluebutton/bbb-playback/blob/1adc0e4ed21cdf51084100ef23dded00cf5f66e1/src/utils/builder.js#L252-L256

An old recording (2.2) has polls that look like this:
```xml
    <g xmlns="http://www.w3.org/2000/svg" id="image1-draw1" class="shape" timestamp="10.8" undo="-1" shape="image1-poll1" style="visibility:hidden">
      <rect x="1058.0" y="782.12" width="540.0" height="115.88" fill="white" stroke="black" stroke-width="4"/>
      <image height="544.0" width="119.88" x="1600" y="780.12" transform="rotate(90, 1600, 780.12)" xlink:href="presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1601651923237/poll_result1.svg" xmlns:xlink="http://www.w3.org/1999/xlink"/>
    </g>
```
but newer recordings (2.3) instead have polls that look like this:
```xml
    <g xmlns="http://www.w3.org/2000/svg" id="image1-draw1" class="shape" timestamp="11.3" undo="-1" shape="image1-poll1" style="visibility:hidden">
      <image width="544.0" height="179.82" x="1056.0" y="720.18" xlink:href="presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1601640367716/poll_result1.svg" xmlns:xlink="http://www.w3.org/1999/xlink"/>
    </g>
```

The newer scripts render the poll using a helper tool that generates an opaque image with the correct rotation, so the extra `<rect>` and the transform on the `<image>` are no longer needed. But since the pattern doesn't match in the code, the bbb-playback format ignores the poll.

To be honest, why does bbb-playback need to know what type a shape is? Shouldn't it just be displaying them as-is? It would be a lot easier to handle new shapes if they only had to be added to the processing script and then they'd show up in the playback automatically.

**Comment by pedrobmarin** [comment]
Another pro on having the playback building the visual data is that we could better handle things like this https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
