### ISSUE TITLE
Make the layout adapative depending on the screen resolution

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bbb-playback#81]
Currently if we play the recordings on HD, Full HD and 4K screen the ratio of the components are not maintained. As example the left bar with camera and chat is smaller in 4K screens, it should have the same width ratio as HD and so on.

**Comment by pedrobmarin** [comment]
It has the same pixel dimension. How does the client handles the problem you described?

**Comment by pedrobmarin** [comment]
Closing this since there was no feedback on it. The sidebar follows the former playback and client design. You can still manipulate it's dimension zooming in and out using the browser native tools.
